### ISSUE TITLE
ssr使用免费订阅网站获取节点，使用chrome无法正常访问google

### ISSUE THREAD

**Issue by daaaaaaaaaaa** [freefq/free#114]
用google搜索，会显示检测到可能机器行为，不是正常用户搜索。请问这是节点本身的问题吗？

**Comment by freefq** [comment]
ssr节点估计有大半年我没怎么用了… 
google搜索出来人机验证，倒是常见，节点IP被滥用就会有

**Comment by daaaaaaaaaaa** [comment]
> ssr节点估计有大半年我没怎么用了… 
> google搜索出来人机验证，倒是常见，节点IP被滥用就会有

好吧，谢谢回答
