### ISSUE TITLE
订阅节点每隔四小时准时更新

### ISSUE THREAD

**Issue by daaaaaaaaaaa** [freefq/free#118]
有点好奇大佬是怎么实现的？？

**Comment by freefq** [comment]
用定时任务crontab
crontab -e
*/4 * * * * python /opt/update.py

**Comment by daaaaaaaaaaa** [comment]
> 用定时任务crontab
> crontab -e
> */4 * * * * python /opt/update.py
部署在linux上面的crontab吗?
嗯嗯大概知道了，感谢回答。

**Comment by freefq** [comment]
这里敲错了 变成4分钟一次了
* */4 * * *
这样才是4小时一次
