### ISSUE TITLE
啊哇哇哇，突然就多了這麽多大陸的伺服器啊！

### ISSUE THREAD

**Issue by wazxu** [freefq/free#122]
鄙人自知沒資格對該項目説三道四的，您就看我像是在用鰓呼吸的胖頭魚嘛。
我自己是一條都不敢用的。

**Comment by freefq** [comment]
那就不要用了

**Comment by wazxu** [comment]
> 那就不要用了

你又何必要關主題呢？

**Comment by wazxu** [comment]
再多説一句吧，希望伺服器別名裏的描述能夠嚴謹一些。
出現過幾次寫著來自美國，Ping實際為上海。

**Comment by samleong123** [comment]
> 再多説一句吧，希望伺服器別名裏的描述能夠嚴謹一些。
> 出現過幾次寫著來自美國，Ping實際為上海。

有些是中国国内中转
因为通常他们的broadband 国际线路晚高峰会比较差
所以需要一个中国国内IP中转
这个中转优化了海外线路
所以实际上你ping看到这样可是你speedtest的话发现是海外的IP
