### ISSUE TITLE
bulink自建节，点没有ipv6吗？

### ISSUE THREAD

**Issue by Chem2080** [freefq/free#155]
最近用Google老是人机验证，在v2rayNG里面开启ipv6优先之后还是一样的，节点没有ipv6吗？

顺便一提，用自建节，点看油管有不少广告😂，基本上每几个视频就有

**Comment by Chem2080** [comment]
不过bulink真的是我用过的最好的vmess

**Comment by freefq** [comment]
现在没有ipv6

**Comment by Chem2080** [comment]
> 现在没有ipv6
> 速度还行吧，谢谢

速度没毛病，就是没有ipv6比较🥚疼
