### ISSUE TITLE
每年开会的时候都这样

### ISSUE THREAD

**Issue by das3641** [freefq/free#17]
每年开会的时候都这样，经典时间经典问题了，半个月以后就正常了，目前ss，ssr和vmess，vless都是识别了的

**Comment by PeakGymnast** [comment]
全挂ᥬ😫᭄

**Comment by rprx** [comment]
张口就来，带上 VLESS，协议结构和运行原理搞明白了吗？

**Comment by lin4007** [comment]
有些基于openvpn的翻墙软件没受到任何影响。

**Comment by chenjunbo** [comment]
会不会是端口被屏蔽了

**Comment by das3641** [comment]
> 张口就来，带上 VLESS，协议结构和运行原理搞明白了吗？

TLS咋了，一个破网站，就一个nginx欢迎页，一天几十上百G的流量，当GFW的大数据不存在，骗鬼呢

**Comment by das3641** [comment]
> 张口就来，带上 VLESS，协议结构和运行原理搞明白了吗？
--------------------------------------------------------------------
你不会以为是内容识别吧，行为识别和内容识别两个概念，搞清楚再来张口就来
TLS咋了，一个破网站，就一个nginx欢迎页，一天几十上百G的流量，当GFW的大数据不存在，骗鬼呢

**Comment by rprx** [comment]
@das3641 

所以你只挂个 Nginx 欢迎页一天跑几十上百G的流量是 VLESS 的错？？？流量异常和协议被识别是两个概念。

**Comment by das3641** [comment]
> @das3641
> 
> 所以你只挂个 Nginx 欢迎页一天跑几十上百G的流量是 VLESS 的错？？？流量异常和协议被识别是两个概念。

---------------------------
所以你引以为豪的吹jb的高大上，高科技VLESS在现在也是封了一大片，流量异常不也是被GFW封了，不是识别了？去学学语文行吗

**Comment by das3641** [comment]
> @das3641
> 
> 所以你只挂个 Nginx 欢迎页一天跑几十上百G的流量是 VLESS 的错？？？流量异常和协议被识别是两个概念。
---------------------------------------
所以你引以为豪的吹jb的高大上，高科技VLESS在现在也是封了一大片，流量异常不也是被GFW封了，不是识别了？去学学语文行吗

**Comment by rprx** [comment]
@das3641 

你 TM 是有病吧？？？听懂我在说什么了吗？

1. 我这里多个渠道没有 VLESS 被大规模封锁的报告，上面也说了 Trojan 没挂，原理一样。

2. 给个 TLS 连接，墙说这是 VLESS，这才能说是协议被识别，有吗？你的原话是 VLESS 是识别了的。

3. **还是那句话，你只挂个 Nginx 欢迎页一天跑几十上百G的流量，自己搞出流量不对等异常是 VLESS 的错？？？你怎么不在 80 端口跑 TLS？？？这只取决于你怎么用，和 VLESS 有个 JB 关系？换了 Trojan 给傻子用也一样。**

**Comment by das3641** [comment]
> @das3641
> 
> 你 TM 是有病吧？？？听懂我在说什么了吗？
> 
> 1. 我这里多个渠道没有 VLESS 被大规模封锁的报告，上面也说了 Trojan 没挂，原理一样。
> 2. 给个 TLS 连接，墙说这是 VLESS，这才能说是协议被识别，有吗？你的原话是 VLESS 是识别了的。
> 3. **还是那句话，你只挂个 Nginx 欢迎页一天跑几十上百G的流量，自己搞出流量不对等异常是 VLESS 的错？？？你怎么不在 80 端口跑 TLS？？？这只取决于你怎么用，和 VLESS 有个 JB 关系？换了 Trojan 给傻子用也一样。**

-------------------
每年开会的时候都这样，经典时间经典问题了，半个月以后就正常了，目前ss，ssr和vmess，vless都是识别了的
以上原话，有说协议识别？
我说今晚有人马出殡，你对号入座你妈出殡，那好，今晚你妈出殡行了吧
