### ISSUE TITLE
请停止对Lncn.org站点节点的分发，谢谢！

### ISSUE THREAD

**Issue by tianfangdao** [freefq/free#178]
如题，这里是Lncn站务，想与朋友述说一些苦衷，希望朋友能花点时间阅览一下。
关于节点过量的分发，导致节点的可用性急剧降低，这样分享目的的本身就被破坏了。
Lncn是个小站，支撑不起太多的使用人数，希望能得到您的体谅。

**Comment by freefq** [comment]
已邮件确认，已把贵站剔除出爬取list
