### ISSUE TITLE
张口就来，带上 VLESS，协议结构和运行原理搞明白了吗？

### ISSUE THREAD

**Issue by das3641** [freefq/free#18]
张口就来，带上 VLESS，协议结构和运行原理搞明白了吗？

_Originally posted by @rprx in https://github.com/freefq/free/issues/17#issuecomment-716506056_
----------------------------------
你不会以为识别了指的是能解密内容吧，谁张口就来。是行为识别而已，上网行为管理和内容识别本身就两个概念

**Comment by rprx** [comment]
https://github.com/freefq/free/issues/17#issuecomment-716949080
