### ISSUE TITLE
这个报错

### ISSUE THREAD

**Issue by pang1534174412** [freefq/free#187]
![image](https://user-images.githubusercontent.com/75722689/125916555-c504697c-91a9-4996-8658-c9c2244d018f.png)
2021/07/16 16:21:52 [Warning] [1754771045] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)

**Comment by freefq** [comment]
大概率是选择的节点失效不可用了，换一个节点再试试。

如何快速的选择有效节点？
批量选中导入节点（可以Ctrl+a），右键菜单中选择测试服务器真连接延迟（快捷键是Ctrl+r），从测试结果中选择延迟比较低的节点设为活动服务器（Enter）。

**Comment by pang1534174412** [comment]
但是我发给我朋友节点他就可以使用，在我的电脑上就不可以

**Comment by pang1534174412** [comment]
> 大概率是选择的节点失效不可用了，换一个节点再试试。
> 
> 如何快速的选择有效节点？
> 批量选中导入节点（可以Ctrl+a），右键菜单中选择测试服务器真连接延迟（快捷键是Ctrl+r），从测试结果中选择延迟比较低的节点设为活动服务器（Enter）。

但是我发给我朋友节点他就可以使用，在我的电脑上就不可以

**Comment by pang1534174412** [comment]
> 大概率是选择的节点失效不可用了，换一个节点再试试。
> 
> 如何快速的选择有效节点？
> 批量选中导入节点（可以Ctrl+a），右键菜单中选择测试服务器真连接延迟（快捷键是Ctrl+r），从测试结果中选择延迟比较低的节点设为活动服务器（Enter）。

而且我的节点是在鸡场买的，星期一的时候还可以使用，这两天就不可以了，我在想会不会是我的电脑的问题。因为我的电脑这几天都没有关机，都是睡眠的

**Comment by freefq** [comment]
这你还是去问你买的鸡场是不是限制登录设备这些吧。。。
