### ISSUE TITLE
我找到个分享v2ray节点的网站

### ISSUE THREAD

**Issue by SNWCreations** [freefq/free#188]
作者，看看这个网站 http://www.gaofumei.net/networks/10812.html
不知道作者大大会不会研究这个网站，爬取一下awa

**Comment by FairyWorld** [comment]
> 作者，看看这个网站 http://www.gaofumei.net/networks/10812.html
> 不知道作者大大会不会研究这个网站，爬取一下awa

我试了下全部不可用

**Comment by freefq** [comment]
现在对同样做免费资源聚合的网站已经没多大意思了，这种还要回复可见的就更没兴趣了

**Comment by ChiefWang93** [comment]
这种免费又回复的时效性不咋好。如果这样找不如  谷歌搜    “free proxies”“目前共有抓取源”   直接找节点池，然后转换为各种订阅链接。
