### ISSUE TITLE
8/1 整个内网无法打开网页？？？

### ISSUE THREAD

**Issue by kitkw** [freefq/free#196]
东莞的。有人同样状况吗？？连百度这些也是拒绝访问的，部分网站能打开但全网都加载不了视频。
但外网就完全正常，也试了关了节点 没用。
是发生什么大事吗？？

**Comment by kitkw** [comment]
> 东莞的。有人同样状况吗？？连百度这些也是拒绝访问的，部分网站能打开但全网都加载不了视频。
> 但外网就完全正常，也试了关了节点 没用。
> 是发生什么大事吗？？

**Comment by freefq** [comment]
你用的是bulink自建节点吧，我设置了屏蔽所有国内网站防止用免费节点来刷量，用PAC模式就好了。

**Comment by kitkw** [comment]
> 你用的是bulink自建节点吧，我设置了屏蔽所有国内网站防止用免费节点来刷量，用PAC模式就好了。

没事了！是路由的里面的是广告插件GodProxy问题。今天突然就抽了关闭后正常，但奇怪是为什么只影响内网...................
