### ISSUE TITLE
求助，无论用什么节点都翻不出去，但用v2ray自带的测试能成功

### ISSUE THREAD

**Issue by huajiworld** [freefq/free#197]
如题，是不是我v2ray配置错了

**Comment by ChiefWang93** [comment]
使用clash  客户端吧！  我用着良好

**Comment by freefq** [comment]
测试节点可用性的时候不要用ping或者tcping，这两个只是检测延迟，真连接延迟和测服务器速度才能知道是否节点依然可用。

感觉我需要把自建节点放最前面好让大家上手容易点。。

如何快速的选择有效节点？
批量选中导入节点（可以Ctrl+a），右键菜单中选择测试服务器真连接延迟（快捷键是Ctrl+r），从测试结果中选择延迟比较低的节点设为活动服务器（Enter）。
