### ISSUE TITLE
作者你好。

### ISSUE THREAD

**Issue by vikingml** [freefq/free#2]
V2RAY的节点我复制之后，在win客户端无法粘贴是什么原因？请赐教。谢谢

**Comment by freefq** [comment]
点V2RayN界面左上角“服务器”，然后下拉菜单选“从剪切板批量导入URL”。刚测试可以导入。
注意复制整行，带上“vmess://”。简单操作就是Ctrl+A整个页面全选，Ctrl+C复制，然后点从剪切板批量导入。

**Comment by vikingml** [comment]
谢谢您细心指导！

freefq <notifications@github.com> 于2020年8月15日周六 下午11:34写道：
