### ISSUE TITLE
牛逼

### ISSUE THREAD

**Issue by i3009juma62** [freefq/free#221]
谷歌云盘上传文件，速度就没掉下20m/s过，平均速度70m/s，最快速度123m/s。比国内云盘的最高50m/s快的多，一个5g文件10分钟即可上传完毕。这还只是免费节点。推荐大家使用。
![1](https://user-images.githubusercontent.com/88968437/131276257-15b7f257-9502-4f99-af0b-981f98a58402.jpg)

**Comment by i3009juma62** [comment]
改一下，最高速度127mb/s

**Comment by i3009juma62** [comment]
别以为免费的流量只有5个g。
![批注 2021-08-30 103756](https://user-images.githubusercontent.com/88968437/131277552-f3665f5e-ae10-4bea-9018-2c34109ca120.jpg)

**Comment by i3009juma62** [comment]
提供7个g免费流量的机场很少，再加上速度很快，还允许用临时邮箱重复注册，请大家珍惜。

**Comment by ChiefWang93** [comment]
速度与具体的带宽，运营商，位置有关。 他的5G只是自建节点。其他的节点并不算在总量内，能不能用看运气。

**Comment by i3009juma62** [comment]
我用的就是自建。系统有个bug，可以偷流量。

**Comment by i3009juma62** [comment]
你看那里怎么写的，只计自建节点。

**Comment by freefq** [comment]
我想把你的号给删了。。。
