### ISSUE TITLE
牛逼的bulink

### ISSUE THREAD

**Issue by cjiwjfijrehv** [freefq/free#223]
恭喜bulink，google上传云盘129m/s新纪录，平均100m/s新纪录。5g文件上传8分钟新纪录。这是报复性上传。今天我用临时邮箱注册了6个账号，全被删了。我是来发泄的，这次文件没上传完就被删除账号了。但我依然里用了一个偷流量bug上传完毕并已最高124m/s和110m/s在1分钟内硬生生的上传了一个500m的文件。
![1](https://user-images.githubusercontent.com/89773535/131312400-8ecb5550-1840-4204-80d7-0d2d8cc89850.jpg)
![](https://user-images.githubusercontent.com/89773535/131312423-b2abc65b-be15-45cc-a9f2-38d05e9bb1db.jpg)
偷流量漏洞如下：（此账号已删）
![12](https://user-images.githubusercontent.com/89773535/131312457-6d5219b1-dc5c-43c0-95eb-01e8f50e44d9.jpg)
感谢bulink的7gb流量。也感谢129mbps的速度。我喜欢你，又讨厌你。

**Comment by cjiwjfijrehv** [comment]
为防被删，有一个网页存档：https://web.archive.org/web/20210830090429/https://github.com/freefq/free/issues/223（需翻墙）

**Comment by cjiwjfijrehv** [comment]
为防被删，有一个网页存档（需翻墙）：https://web.archive.org/web/20210830090429/https://github.com/freefq/free/issues/223

**Comment by cjiwjfijrehv** [comment]
被用存档（无需翻墙）：https://archive.ph/JvmQN

**Comment by freefq** [comment]
你真的太闲了。。。
