### ISSUE TITLE
节点更新404 已注册账号无法登录了

### ISSUE THREAD

**Issue by Lemon-Fruit** [freefq/free#225]
今天更新节点发现404了，网站也无法登录了

**Comment by freefq** [comment]
最近删了一些非主流邮箱而且没有认证的账号，应该是账号没了

**Comment by Lemon-Fruit** [comment]
> 最近删了一些非主流邮箱而且没有认证的账号，应该是账号没了
哦哦，那我需要重新注册一个账号了吗？

**Comment by Lemon-Fruit** [comment]
> 最近删了一些非主流邮箱而且没有认证的账号，应该是账号没了

哦哦，那我需要重新注册一个账号了吗？

**Comment by chendataor** [comment]
> 最近删了一些非主流邮箱而且没有认证的账号，应该是账号没了

怎么确定自己的是不是被 删掉了呢，现在访问bluelink.xyq打不开，bluelink.me报404

**Comment by freefq** [comment]
bulink.me 报404那就是没找到用户就是号没了。 bulink.xyz会经常打不开？？
