### ISSUE TITLE
最近是因为特殊时期吗 感觉赞助节点少了很多 而且订阅的赞助节点大多数都无法正常工作

### ISSUE THREAD

**Issue by MilesPoupart** [freefq/free#246]

**Comment by Mazakanull** [comment]
64，10月1都是特殊时期，节点大量封锁

**Comment by jikangrong2021** [comment]
建议使用云帆vpn作为备用

Mazaka ***@***.***> 于 2021年10月2日周六 12:12写道：

**Comment by freefq** [comment]
不好意思最近有点忙没怎么管这里，节点也确实是少了不少。
但你更新订阅，拿到的基本上都是可用的节点，不会有说是大部分不可用的情况。。
