### ISSUE TITLE
bulink 无法登入

### ISSUE THREAD

**Issue by LeMonThELord** [freefq/free#250]
bulink 无法登入
chrome 记住的密码无效
提示：请重新填写信息！
申请忘记密码收不到邮件
QQ邮箱

**Comment by LeMonThELord** [comment]
看了看之前的issue，可能是被误删了，clash默认间隔1h更新订阅，有时候手动刷几次很容易就会到一天20+次，是不是因为这个被误封了。如果是的话有什么办法解决吗？

**Comment by freefq** [comment]
嗯，应该是号没了。
最近没删订阅次数过多的，也就没因为这个删过多少，倒是写了个判断把瞬时流量大的删了几个。

**Comment by LeMonThELord** [comment]
> 嗯，应该是号没了。 最近没删订阅次数过多的，也就没因为这个删过多少，倒是写了个判断把瞬时流量大的删了几个。

啊这。。瞬时流量大也会删的嘛。。那4k YouTube是不是不能看 QAQ

**Comment by Xinyue-Wong** [comment]
(gmail)
bulink 无法登入，订阅的节点更新失败
chrome 记住的密码无效
提示：请重新填写信息！
申请忘记密码收不到邮件

**Comment by freefq** [comment]
> > 嗯，应该是号没了。 最近没删订阅次数过多的，也就没因为这个删过多少，倒是写了个判断把瞬时流量大的删了几个。
> 
> 我试了一下，不能用原来的邮箱重新注册了？提示已经注册过，是不是相当于ban掉了？

删掉的号会保留邮箱注册记录，删掉了继续用原邮箱能注册那不是鼓励你们滥用……

**Comment by freefq** [comment]
> (gmail) bulink 无法登入，订阅的节点更新失败 chrome 记住的密码无效 提示：请重新填写信息！ 申请忘记密码收不到邮件

最近是删了几个几分钟就把5G流量都用光的号，除了下载我不知道有哪个网站这么耗流量，看油管4K也做不到
