### ISSUE TITLE
最近是出什么问题了吗？这几天任何节点都连不上

### ISSUE THREAD

**Issue by GLORYFeonix** [freefq/free#276]
大概是6号开始的

**Comment by fighting-noah** [comment]
> 大概是6号开始的

用的什么TZ，可否分享一下 ？

**Comment by GLORYFeonix** [comment]
> > 大概是6号开始的
> 
> 用的什么TZ，可否分享一下 ？

你在这个repo里问我用的什么，会不会有点奇怪。。。

**Comment by fighting-noah** [comment]
> > > 大概是6号开始的
> > 
> > 
> > 用的什么TZ，可否分享一下 ？
> 
> 你在这个repo里问我用的什么，会不会有点奇怪。。。

都链接不上，你还能用？

**Comment by GLORYFeonix** [comment]
> > > > 大概是6号开始的
> > > 
> > > 
> > > 用的什么TZ，可否分享一下 ？
> > 
> > 
> > 你在这个repo里问我用的什么，会不会有点奇怪。。。
> 
> 都链接不上，你还能用？

6号后才不能啊。。。

**Comment by fighting-noah** [comment]
> > > > > 大概是6号开始的
> > > > 
> > > > 
> > > > 用的什么TZ，可否分享一下 ？
> > > 
> > > 
> > > 你在这个repo里问我用的什么，会不会有点奇怪。。。
> > 
> > 
> > 都链接不上，你还能用？
> 
> 6号后才不能啊。。。

是6号不能，不是一直现在都不能用吗，最起码现在是不是用的其他的，难道没用吗。。。

**Comment by GLORYFeonix** [comment]
> > > > > > 大概是6号开始的
> > > > > 
> > > > > 
> > > > > 用的什么TZ，可否分享一下 ？
> > > > 
> > > > 
> > > > 你在这个repo里问我用的什么，会不会有点奇怪。。。
> > > 
> > > 
> > > 都链接不上，你还能用？
> > 
> > 
> > 6号后才不能啊。。。
> 
> 是6号不能，不是一直现在都不能用吗，最起码现在是不是用的其他的，难道没用吗。。。

至少此时此刻没有

**Comment by freefq** [comment]
11月8日至11日开会
