### ISSUE TITLE
网路恢复了是不是，谢谢大佬🙏🙏🙏🙏🙏

### ISSUE THREAD

**Issue by roy0011** [freefq/free#278]

**Comment by hu516** [comment]
没有吧，bulink网站和自建节点都连不上了

**Comment by Li15838287467** [comment]
我的可以连上，能访问外网。但是访问国内的它提示下面这些。 你们有遇到过吗
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:
Could not load template file no-server-data or one of its included components.
Please contact your proxy administrator.
If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).
