### ISSUE TITLE
订阅网址不好用🥺

### ISSUE THREAD

**Issue by roy0011** [freefq/free#283]

**Comment by freefq** [comment]
刚V2rayN测试fastgit订阅地址更新没有问题

**Comment by Lijingze2019** [comment]
+1，我的bulink上的订阅链接不能用了，fastgit可以。然后在bulink.xyz发现账号登不上去，忘记密码也收不到邮件

**Comment by Wisoer** [comment]
+1， 注册的时候显示已经注册，但是登录不了，忘记密码收不到邮件。

**Comment by 1153439431** [comment]
> +1， 注册的时候显示已经注册，但是登录不了，忘记密码收不到邮件。

我也是的
