### ISSUE TITLE
怎么把这个项目，从我的仓库里去掉

### ISSUE THREAD

**Issue by youdmeng** [freefq/free#29]
我不是开发者，我没有fork，我没有star，我没有watch

 **请告诉我，怎么从我的库里把它去掉**

![Screenshot_20201107-221836_Chrome.jpg](https://user-images.githubusercontent.com/38751158/98443701-f9117e80-2147-11eb-9822-72eddfaedfac.jpg)

**Comment by freefq** [comment]
不好意思，不太清楚你遇到的项目错误显示的bug怎么导致的。可以尝试fork后删除，star后取消

**Comment by youdmeng** [comment]
> 不好意思，不太清楚你遇到的项目错误显示的bug怎么导致的。可以尝试fork后删除，star后取消

我也不知道了
