### ISSUE TITLE
请教一下大家，最近使用情况……

### ISSUE THREAD

**Issue by momi0099** [freefq/free#290]
昨天开始，无法打开YouTube，显示建立安全连接失败，努力了下，正常进入了，但视频无法播放，一直是转圈状态，进直播也是转圈，但边上的对话框能正常显示留言……
除了youtube无法播放视频外，剩下的网站都能正常使用……
想请教下，大家有遇到这情况吗，有什么方法修复吗……

**Comment by Lee-7723** [comment]
我在使用youtube-dl的时候发现出现了ssl 1131的错误，貌似是https的问题，换节点后没有此问题，所以建议请排除一下是节点问题还是本机设置问题。
（用v2rayNG的时候发现在电脑上挺好用的节点在手机上连上没速度，感觉是自己设置的问题，有人遇到类似问题吗？）

**Comment by zakizou** [comment]
> 我在使用youtube-dl的时候发现出现了ssl 1131的错误，貌似是https的问题，换节点后没有此问题，所以建议请排除一下是节点问题还是本机设置问题。 （用v2rayNG的时候发现在电脑上挺好用的节点在手机上连上没速度，感觉是自己设置的问题，有人遇到类似问题吗？）

有可能是数据运营商的区别
