### ISSUE TITLE
正常邮箱注册的BuLink账号也被回收了

### ISSUE THREAD

**Issue by 396930154** [freefq/free#301]
之前用临时邮箱注册了发现账号被回收，后来换正常的outlook邮箱账号注册也被回收账号了，不解，邮箱账号 wowlonicc@outlook.com

**Comment by freefq** [comment]
那还是你用的环境注册过多个账号了。。

这个账号给恢复了

**Comment by 396930154** [comment]
感谢！

**Comment by iieunx** [comment]
我可以重新注册一下吗？当时忘记看邮箱了 没认正 我是QQ邮箱注册的 还挺常用 希望解一下1363433893@qq.com
