### ISSUE TITLE
安全问题

### ISSUE THREAD

**Issue by mdd-star** [freefq/free#302]
请问使用免费的结点会有安全问题吗，比如说密码泄露这种的问题

**Comment by freefq** [comment]
不太像是码农问的问题…

https://zh.wikipedia.org/wiki/%E8%B6%85%E6%96%87%E6%9C%AC%E4%BC%A0%E8%BE%93%E5%AE%89%E5%85%A8%E5%8D%8F%E8%AE%AE
HTTPS报文中的任何东西都被加密，包括所有报头和荷载。除了可能的选择密文攻击之外，一个攻击者所能知道的只有在两者之间有一连接这一事实。

去年的在线代理倒是会有安全问题

**Comment by mdd-star** [comment]
> 不太像是码农问的问题…
> 
> https://zh.wikipedia.org/wiki/%E8%B6%85%E6%96%87%E6%9C%AC%E4%BC%A0%E8%BE%93%E5%AE%89%E5%85%A8%E5%8D%8F%E8%AE%AE HTTPS报文中的任何东西都被加密，包括所有报头和荷载。除了可能的选择密文攻击之外，一个攻击者所能知道的只有在两者之间有一连接这一事实。
> 
> 去年的在线代理倒是会有安全问题

不好意思刚刚接触不是很懂
