### ISSUE TITLE
求助：bulink.xyz无法添加clash订阅链接

### ISSUE THREAD

**Issue by Cmgdels** [freefq/free#306]
我使用clash来翻墙，可是我添加订阅URL时，它报错了：Get "https://bulink.me/sub/m5aep/cl": x509: certificate has expired or is not yet valid: current time 2021-12-21T22:30:30Z is after 2021-09-30T14:01:15Z
我翻译了下，说是证书过期或无效，您看看可不可以帮助我一下

**Comment by freefq** [comment]
很奇怪，这里提示的证书过期了，但实际bulink.me证书没有过期……

**Comment by Cmgdels** [comment]
#

> 我用clash来翻墙，可是我添加订阅URL时，它报错了：Get " https://bulink.me/sub/m5aep/cl ": x509: certificate has expired or is not yet valid: current time 2021- 12-21T22:30:30Z是在2021-09-30T14:01:15Z之后 我翻译了下，说是证书过期或失效，你看看可不可以帮我看看

**Comment by Cmgdels** [comment]
> 很奇怪，这里提示的证书过期了，但实际bulink.me证书没有过期……

如何解决呢

**Comment by freefq** [comment]
https://letsencrypt.org/zh-cn/docs/dst-root-ca-x3-expiration-september-2021/

看起来是系统太老的问题，尝试更新系统，更新Clash到最新版本看看

**Comment by Cmgdels** [comment]
> https://letsencrypt.org/zh-cn/docs/dst-root-ca-x3-expiration-september-2021/
> 
> 看起来是系统太老的问题，试点更新系统，更新冲突到最新版本看看

clash已经更新到最新版本了，系统可能没办法更新了......
