### ISSUE TITLE
oneclick苹果美区账号可以下载吗？

### ISSUE THREAD

**Issue by yuanyangwangTJ** [freefq/free#314]
准备使用苹果设备，因为注册外区账号不易，所以想问oneclick除了港区外美区可以下载吗？

**Comment by freefq** [comment]
印象中是可以的
其实直接更改苹果账号地区就行
https://support.apple.com/zh-cn/HT201389

**Comment by yuanyangwangTJ** [comment]
> 印象中是可以的 其实直接更改苹果账号地区就行 https://support.apple.com/zh-cn/HT201389

感谢！
