### ISSUE TITLE
最近无法更新订阅：基础连接已经关闭

### ISSUE THREAD

**Issue by 838239178** [freefq/free#321]
**v2rayN 3.27** 最近无法更新订阅 虽然bulink路线还可用
```
更新订阅开始
1->开始获取订阅内容
基础连接已经关闭: 发送时发生错误。
```
用的是bulink的订阅地址

**Comment by freefq** [comment]
偶发的吧
bulink.me订阅域名，服务器IP还没有被墙

**Comment by 838239178** [comment]
今天仍然不能更新订阅

**Comment by freefq** [comment]
> 今天仍然不能更新订阅

做了个反代站，把订阅链接中的bulink.me换成burstlinker.com试试

**Comment by 838239178** [comment]
还是不行 基础连接已关闭

**Comment by milo-wjh** [comment]
今天我这也出现了这问题   bulink.me 可以登录
