### ISSUE TITLE
基本上没一个可以用

### ISSUE THREAD

**Issue by 838239178** [freefq/free#328]
真链接测试：（这是我的问题还是服务器被墙了）
![image](https://user-images.githubusercontent.com/55338151/153210135-8545b9da-4b52-4106-8097-2ddf8ae78fd2.png)

**Comment by 838239178** [comment]
而且我没看见新增加的日本服务器 需要付费吗

**Comment by freefq** [comment]
测速时候可以少选几个节点试试，结果就不容易出现批量全是操作超时或其它无法连接服务器错误。

用github开头的采集节点的话，需要时常更新订阅，保持最新的可用节点，这里是4小时更新一次。你流量需求不大，不看视频可以用bulink自建节点，长期可用

新增的服务器是赞助节点

**Comment by ecian1** [comment]
bulink 注册不了 注册时候时候弹出 ：此网络最近已经注册账号？？？？？



在 2022-02-09 22:05:34，"freefq" ***@***.***> 写道：

测速时候可以少选几个节点试试，结果就不容易出现批量全是操作超时或其它无法连接服务器错误。

用github开头的采集节点的话，需要时常更新订阅，保持最新的可用节点，这里是4小时更新一次。你流量需求不大，不看视频可以用bulink自建节点，长期可用

新增的服务器是赞助节点
