### ISSUE TITLE
自建节点不能正常使用

### ISSUE THREAD

**Issue by android-1995** [freefq/free#330]
![image](https://user-images.githubusercontent.com/35674533/153689932-d6879bf1-a816-4612-ba23-51ea2da8c92e.png)
![image](https://user-images.githubusercontent.com/35674533/153689953-2efbe766-1650-446a-9c8e-f578d864c1db.png)

@freefq 救救我

**Comment by freefq** [comment]
我这刚看是还剩三个可用 已换端口修复

墙现在处于活跃期了。。。

**Comment by android-1995** [comment]
![image](https://user-images.githubusercontent.com/35674533/153700404-0f8414da-3b17-44dd-847d-4e9a939863ba.png)
我刚更新了，还是全挂了- -
跟地区有关吗？

**Comment by android-1995** [comment]
不计流量的反倒还大部分能用😂

**Comment by android-1995** [comment]
已解决，是v2rayN没更新到最新导致的
