### ISSUE TITLE
请问能否提供支持SSL/https协议的ip与端口?

### ISSUE THREAD

**Issue by a15355447898a** [freefq/free#370]
本人linux用户,经常需要用ProxyChains来代理,但是这个软件只支持SSL/https协议...

**Comment by freefq** [comment]
不知道你是不是搞错了节点的用法。Vmess的伪装协议只是v2ray的客户端与服务器通信用。
你没法用ProxyChains直连v2ray服务器，而是要通过本地v2ray客户端，在proxychains配置文件中设置v2ray的监听端口如:
socks5 127.0.0.1 1080

**Comment by a15355447898a** [comment]
谢谢，了解了
