### ISSUE TITLE
在自定义节点订阅中，希望增加只订阅trojan的订阅地址

### ISSUE THREAD

**Issue by jacklee789** [freefq/free#40]
目前在自定义节点订阅中是三个订阅地址：订阅SSR，订阅Vmess(含SS/Trojan)，只订阅Vmess

希望增加只订阅Trojan的订阅地址

**Comment by freefq** [comment]
收到
后面会添加只订阅ss和只订阅trojan，爬到的trojan节点不多，还以为没有需要这个

**Comment by freefq** [comment]
已添加
