### ISSUE TITLE
突然用不了了~~~wwwww

### ISSUE THREAD

**Issue by MaeStrive** [freefq/free#407]
前几天用的好好的，今天突然用不了，如何解决啊啊
![在这里插入图片描述](https://img-blog.csdnimg.cn/2427cd8caed34405ae9efe904f519c42.png)

**Comment by MaeStrive** [comment]
解决了。。重启了以下就好了 感谢！！！

**Comment by freefq** [comment]
项目首页github.com/freefq开头的采集节点基本就一两天的有效期如果你去https://burstlinker.com 注册过账号
