### ISSUE TITLE
节点大面积爆炸

### ISSUE THREAD

**Issue by HRxiaohu** [freefq/free#417]
![image](https://user-images.githubusercontent.com/63327671/171989565-435e4627-8af8-4fb8-ac79-ed795666323b.png)

**Comment by mccation** [comment]
六四



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月4日(周六) 下午3:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [freefq/free] 节点大面积爆炸 (Issue #417)
