### ISSUE TITLE
通过在线代理https://j.bulink.xyz/，如何操作才能下载youtube视频

### ISSUE THREAD

**Issue by jacklee789** [freefq/free#42]
youtube视频已经解析出真实下载地址，通过在线代理 https://j.bulink.xyz/ 可以播放真实下载地址的视频，但不能下载，点击下载按钮没有反应。请问如何操作才能下载？是因为jsproxy的原因导致无法下载吗？

![1](https://user-images.githubusercontent.com/55917636/101750884-94608f80-3b0a-11eb-8f94-efc1802009a8.jpg)

**Comment by freefq** [comment]
jsproxy并不能保证网页所有功能完好，只是便利使用。

youtube视频下载其实有很多工具，像这个https://github.com/ytdl-org/youtube-dl。
你完全可以通过代理下载：youtube-dl --proxy socks5://127.0.0.1:10808 https://www.youtube.com/watch?v=6_gLU_OStK0
你把主页上的节点测速找个快点的，比用jsproxy要强不少的。

**Comment by jacklee789** [comment]
确实有很多下载方式，这里只是想知道这个方式不能下载的原因。谢谢解答。

**Comment by freefq** [comment]
如果有你有兴趣看jsproxy实现原理的话会更清楚为什么不能下载。
https://github.com/EtherDream/jsproxy/blob/master/docs/blogs/js-hook.md

简单讲就是现在网页动态内容很多，js-hook替换链接网址并不能覆盖所有情况。

**Comment by jacklee789** [comment]
EtherDream/jsproxy文章最后介绍了一个国外在线代理 https://www.croxyproxy.com/ 用这个代理可以下载视频，点击下载按钮有反应。这个国外代理的自我介绍中有This web proxy supports Youtube perfectly. 看来确实做到了。希望 https://j.bulink.xyz/  可以学到  https://www.croxyproxy.com/  的黑科技。

**Comment by freefq** [comment]
不能拿工业级别的商用软件跟开源软件比。

曾经尝试去修复原作者提到的在线代理reCAPTCHA无法正常显示的问题，最后还是放弃了。
在线代理永远只是便利使用，费尽心思实现不了的一个功能，用个客户端proxy分分钟解决。(想来这里解决reCAPTCHA不能提高多少在线代理的体验，反而会在镜像站、钓鱼站这类黑灰产行业大放异彩，别做恶)

**Comment by jacklee789** [comment]
明白，谢谢。
