### ISSUE TITLE
来自新用户的小小疑问

### ISSUE THREAD

**Issue by OrsonLee** [freefq/free#424]
首先感谢大佬，这个项目是我遇到的使用最顺畅最稳定更新最快的免费FQ，非常感谢。但我有两个疑问：

一是这些免费节点来自哪里呢？都是大佬写的某种自动爬虫脚本抓取的吗

二是我自己已经租了BWG的VPS，也自己搭建了SS，但是最近IP频繁被墙，又无处咨询，所以想问问是不是VPS+原生SS已经很容易被墙识别并拉黑了？有无最新可靠的自建VPS的技术方向呢

来自一个半小白的真诚感谢和疑问

**Comment by sdjames64157** [comment]
> 首先感谢大佬，这个项目是我遇到的使用最顺畅最稳定更新最快的免费FQ，非常感谢。但我有两个疑问：
> 
> 一是这些免费节点来自哪里呢？都是大佬写的某种自动爬虫脚本抓取的吗
> 
> 二是我自己已经租了BWG的VPS，也自己搭建了SS，但是最近IP频繁被墙，又无处咨询，所以想问问是不是VPS+原生SS已经很容易被墙识别并拉黑了？有无最新可靠的自建VPS的技术方向呢
> 
> 来自一个半小白的真诚感谢和疑问

https://www.youtube.com/watch?v=3ivwonJuqyI 这个链接可以看下

**Comment by freefq** [comment]
1、免费节点都是脚本爬的，你要代码可以github找找，有很多类似项目了
2、是的 用TLS

**Comment by OrsonLee** [comment]
> > 首先感谢大佬，这个项目是我遇到的使用最顺畅最稳定更新最快的免费FQ，非常感谢。但我有两个疑问：
> > 一是这些免费节点来自哪里呢？都是大佬写的某种自动爬虫脚本抓取的吗
> > 二是我自己已经租了BWG的VPS，也自己搭建了SS，但是最近IP频繁被墙，又无处咨询，所以想问问是不是VPS+原生SS已经很容易被墙识别并拉黑了？有无最新可靠的自建VPS的技术方向呢
> > 来自一个半小白的真诚感谢和疑问
> 
> https://www.youtube.com/watch?v=3ivwonJuqyI 这个链接可以看下

很感谢，超级棒的教程。

**Comment by OrsonLee** [comment]
> 

了解，感谢！
