### ISSUE TITLE
怎么莫名其妙就账号被回收了？

### ISSUE THREAD

**Issue by wlc743859910** [freefq/free#452]
怎么莫名其妙就账号被回收了？之前六个线路，前几天看了下一个线路都没有了。
刚进官网想登陆看看是不是挂了呢，结果登录时 提示

账号已回收！
您的账号已被管理员回收，请注意合理使用免费资源！

能恢复下吗？
743859910@qq.com

**Comment by freefq** [comment]
已恢复

**Comment by wlc743859910** [comment]
> 已恢复

名字为 三网 的还是一个都没有

**Comment by freefq** [comment]
> > 已恢复
> 
> 名字为 三网 的还是一个都没有

你有没有尝试拉到最下。。。
