### ISSUE TITLE
请问订阅连接手机上不可用吗？

### ISSUE THREAD

**Issue by kenfuni** [freefq/free#46]
电脑上的v2rayN订阅连接可以正常更新，手机上的v2rayNG订阅连接输进去后更新订阅，但是提示不能用。是手机上有限制吗？

**Comment by freefq** [comment]
一直可用，没做任何限制。
看看订阅链接是否复制黏贴完整

**Comment by kenfuni** [comment]
弄好了，得先出去，然后再更新订阅
