### ISSUE TITLE
自建节点会修改根证书，存在安全问题

### ISSUE THREAD

**Issue by draftman9** [freefq/free#461]
用自建节点时，打开 www.reddit.com 会出现如图所示的安全提示，可以看到根证书被修改了。使用者与所打开的网站不匹配。

![20220912145418](https://user-images.githubusercontent.com/99490289/189591236-ebfc3457-a006-401e-b556-ae7e475212cc.png)

**Comment by freefq** [comment]
这是reddit.com被屏蔽了。节点用https://github.com/StevenBlack/hosts这个hosts文件屏蔽指定的域名。有个自建节点用的是Unified hosts + fakenews + gambling + porn + social版本，把所有社交网站也屏蔽了……
访问这些被屏蔽的站点就会出现根证书的问题，因为流量都到本地443端口了，已更新hosts修复问题
