### ISSUE TITLE
每次新打开时总会弹出如下界面，都需要重新下载才能用

### ISSUE THREAD

**Issue by ysmhyl** [freefq/free#47]
每次打开会弹出弹窗，
Fatal error:init_error_log():cant open logfile:'v2ray_privoxy.log'
但log文件是存在的

![1](https://user-images.githubusercontent.com/37764733/102462537-dc406300-4084-11eb-8222-0c1cc8400242.png)

**Comment by freefq** [comment]
看着像是权限的问题，这个要找V2rayN的原项目作者提issue了
https://github.com/2dust/v2rayN

**Comment by ysmhyl** [comment]
> 看着像是权限的问题，这个要找V2rayN的原项目作者提issue了
> https://github.com/2dust/v2ray

**Comment by ysmhyl** [comment]
> 看着像是权限的问题，这个要找V2rayN的原项目作者提issue了
> https://github.com/2dust/v2rayN

以管理员身份打开可以了😀

**Comment by freefq** [comment]
这年头程序员也太不专业了…… 还会不会修改电脑了
