### ISSUE TITLE
赞助用户过期后如何使用免费节点

### ISSUE THREAD

**Issue by bytesys** [freefq/free#474]
请问赞助用户过期后如何使用免费节点，过期之后显示流量已用完。
注册邮箱：206238015@qq.com

**Comment by freefq** [comment]
已手动重置，但建议考虑自己部署节点，免费自建节点现在只有两条可用，而且负载很高，我试过已经很难连上了。。

**Comment by bytesys** [comment]
> 已手动重置，但建议考虑自己部署节点，免费自建节点现在只有两条可用，而且负载很高，我试过已经很难连上了。。

好的，感谢。另外请问何时能够恢复赞助节点的充值？
