### ISSUE TITLE
最近的节点是不是不可用了啊

### ISSUE THREAD

**Issue by sunbuhui** [freefq/free#49]
从2020/12/20到2020/12/21现在，试了几个节点都不可用啊。
env: v2ray4 + qv2ray

**Comment by freefq** [comment]
刚测速下来，可用率还是有八成的，就是确实很多节点的速度很慢。

测速节点反应不了国内三网各区域的网络速度，所以还是要保留网速慢的节点大家自己测速。

不追求1080P的话可以用注册用BuLink的自建节点，基本看得到就可用。
![测速截图1](https://user-images.githubusercontent.com/66541990/102744491-e3bd8000-4394-11eb-8fe8-2343892cf289.png)

**Comment by sunbuhui** [comment]
@freefq 
![image](https://user-images.githubusercontent.com/33833308/102744741-78c07900-4395-11eb-9448-36b3d2acbb4b.png)
我现在的情况是ping的话和之前正常使用没什么区别，但是访问海外网站的时候就失效了，可能是我这里网络供应商的问题吧。Anyway, 谢谢你的无私分享！

**Comment by sunbuhui** [comment]
可能是我的网络配置/network proxy的问题，不过我已经放弃用v2ray了。。。
