### ISSUE TITLE
为什么我的v2rayN右下角说网络显示未启用，还提示有个错误，访问Google也好慢

### ISSUE THREAD

**Issue by RZL999** [freefq/free#501]
提示错误如下：
2022/11/27 17:14:54 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://aop.ssfree.ru/getweather):  > read tcp 172.31.42.177:52201->144.24.30.237:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://aop.ssfree.ru/getweather):  > read tcp 172.31.42.177:52204->144.24.30.237:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://aop.ssfree.ru/getweather):  > read tcp 172.31.42.177:52206->144.24.30.237:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://aop.ssfree.ru/getweather):  > dial tcp 144.24.30.237:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://aop.ssfree.ru/getweather):  > read tcp 172.31.42.177:52248->144.24.30.237:443: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by handaner** [comment]
解决了吗，我也是这种情况，求分享
