### ISSUE TITLE
mac 系统可以用吗？有没有可以提供靠谱的软件呢？

### ISSUE THREAD

**Issue by gitldy1013** [freefq/free#59]
如题，希望大佬能有办法提供一下。

**Comment by freefq** [comment]
mac下可用:
https://github.com/yanue/V2rayU/releases/download/3.0.0.preview/V2rayU.dmg
项目地址:
https://github.com/yanue/V2rayU

**Comment by gitldy1013** [comment]
感谢 我试试

**Comment by gitldy1013** [comment]
试了一下好像不能用啊 倒入剪切板内容后都显示-1ms

**Comment by freefq** [comment]
不好意思，其实我只是找了个star数多的软件，个人并没有用过，全部不可用这我也不清楚是哪里设置问题了

**Comment by gitldy1013** [comment]
哦哦 没事我再看看也可能我自己的配置问题

**Comment by cqwzls** [comment]
用相应的翻墙客户端添加订阅地址就可以了，常见的MAC端有 Qv2ray， ClashX， V2RayX， V2RayU

有梦想的咸鱼 <notifications@github.com> 于2021年1月22日周五 下午5:36写道：
