### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by chenguoqiang-transportation-boy** [freefq/free#6]
您好，请问这样就行了吗？
![image](https://user-images.githubusercontent.com/59219276/92067021-e68c6900-edd5-11ea-9cd7-3369635b3f6b.png)
但是我访问“谷歌学术”好像还是不行
![image](https://user-images.githubusercontent.com/59219276/92067052-fc019300-edd5-11ea-869c-0d9b6ee18247.png)

**Comment by freefq** [comment]
这是已导入Vmess节点，没有开启代理。
导入节点后，先在主界面设置任一节点为活动服务器。
![设为活动服务器](https://user-images.githubusercontent.com/66541990/92071046-50aa0b80-ede0-11ea-8669-ee5b541db325.png)
然后任务栏右键V2rayN图标，点击启用Http代理。
![开启代理](https://user-images.githubusercontent.com/66541990/92071104-77684200-ede0-11ea-809e-4463099bb7f8.png)
开启http代理，可选自动台历服务器全局模式或PAC模式（建议pac）。
![开启全局](https://user-images.githubusercontent.com/66541990/92071175-a1216900-ede0-11ea-8f85-6cd8ac106c96.png)

这时就可以访问外网了。如不开代理使用需要用到chrome插件 SwitchyOmega。

**Comment by freefq** [comment]
如果依然不能访问，可以尝试切换其它Vmess节点为活跃服务器。主界面有批量测速选项，可以测速后选择合适节点。
![批量测速](https://user-images.githubusercontent.com/66541990/92071439-476d6e80-ede1-11ea-9fc0-7fc4e5e26021.png)

**Comment by chenguoqiang-transportation-boy** [comment]
好的，非常谢谢
