### ISSUE TITLE
节点不好使啊。。。

### ISSUE THREAD

**Issue by HappyCpp** [freefq/free#61]

**Comment by freefq** [comment]
不好使具体是什么表现：连不上？速度慢？

多选节点测试服务器真连接延迟，这个可以测试节点是否真的可用，测试速度块。
多选节点测试服务器速度，这个可以测试节点的速度，测速后选速度在1M/s以上的节点，这个比真连接延迟好用，就是测试速度慢。

**Comment by HappyCpp** [comment]
> 不好使具体是什么表现：连不上？速度慢？
> 
> 多选节点测试服务器真连接延迟，这个可以测试节点是否真的可用，测试速度块。
> 多选节点测试服务器速度，这个可以测试节点的速度，测速后选速度在1M/s以上的节点，这个比真连接延迟好用，就是测试速度慢。

就是节点导入之后连不上

**Comment by freefq** [comment]
可以再详细说一下情况，你用的客户端是V2rayN吗（如果不是，还是强烈建议用V2rayN），可以看一下这个教程https://github.com/freefq/tutorials。

节点导入后，可以Ctrl+A全选节点，Ctrl+T测试服务器速度多选，找测速结果栏数值大的节点用。（就是选中这个节点，按Enter或者右键找到设置为活动服务器）

还有你是否用了Chrome浏览器switchyomega插件，用了的话需要设置插件为系统代理状态，或者自己添加情景模式
