### ISSUE TITLE
推荐稳定的梯子 VPN CLASH

### ISSUE THREAD

**Issue by yanwei5** [freefq/free#653]
https://www.celerlink.buzz/auth/register?code=a95fc0dd50
想用稳定的翻墙工具的朋友可以考虑这个,
价格相对便宜,可白嫖,可试用

**Comment by kawa1909** [comment]
nb

**Comment by kawa1909** [comment]
> https://www.celerlink.buzz/auth/register?code=a95fc0dd50 想用稳定的翻墙工具的朋友可以考虑这个, 价格相对便宜,可白嫖,可试用

哥们这个现在好像用不了了

**Comment by yanwei5** [comment]
我买的年费也用不了了..
![Uploading 1706084411599.jpg…]()
