### ISSUE TITLE
问题请教2

### ISSUE THREAD

**Issue by chenguoqiang-transportation-boy** [freefq/free#7]
非常感谢您的指点，我能够访问外网，可以查看googleschooler了，而且我发现pip命令的更快了太感谢了。

但有一个问题让我担心，想请教一下您，请问您这个翻墙的原理是什么？是会改变电脑的某种配置吗？用一次之后即使关闭v2rayN.exe仍然会起作用吗？因为最近出台了关于“翻墙”违法的事情，我有点怕。

抱歉打扰您了

**Comment by freefq** [comment]
关闭v2rayN.exe后不会起作用。
我们都只是工具的使用者，对原理不甚了解。
翻墙严格意义上不违法，但也要看你翻墙要做什么。翻墙上google scholar不违法，翻墙上twitter发帖要推翻什么什么就违法了。

**Comment by chenguoqiang-transportation-boy** [comment]
哦哦，好的，谢谢您的指点
