### ISSUE TITLE
请教一个问题，某些节点google不能自动登录

### ISSUE THREAD

**Issue by jacklee789** [freefq/free#74]
启动chrome浏览器，google已设置自动登录，多数节点可以自动登录。

但有少数节点（尤其是香港节点）不能自动登录，请问这是什么原理，为什么节点可以阻止google自动登录？谢谢

**Comment by freefq** [comment]
没遇到过你说的问题，猜测是节点使用人数过多触发Google账号安全措施。

**Comment by jacklee789** [comment]
给你的邮箱发了一个节点信息，我这里google不能自动登录，麻烦你看看google能不能自动登录。谢谢
