### ISSUE TITLE
ssr不能设置（没节点了？）

### ISSUE THREAD

**Issue by mikelty** [freefq/free#86]
windows系统，在两个版本（2和4）的ssr上试了如下几步：
启动ssr
从剪切板导入了v2ray的那些节点（我尝试的时候ssr下无节点，v2ray正常工作）
服务器->更新（两个选项，有一个是不通过代理的）
等待了几十秒，无果（小飞机灰色）
重启后无果（小飞机灰色）
感觉错误可能是没有ssr节点所导致的

**Comment by freefq** [comment]
是没有ssr可用节点，现在除了lncn，已经没几个稳定更新ssr免费节点源了。

建议换到v2ray，生态更丰富，iOS也有免费的客户端OneClick了，强烈推荐换。

**Comment by mikelty** [comment]
好的，有想过linux也开一个么

**Comment by freefq** [comment]
用linux我认为都是高玩，自己搜下github一大堆v2ray软件，不需要单列了
