### ISSUE TITLE
希望https://j.bulink.xyz/可以成为croxyproxy.com的前置代理

### ISSUE THREAD

**Issue by jacklee789** [freefq/free#98]
bulink是个人部署，服务器流量不会很多。
croxyproxy是公司部署，服务器流量可以很多。

目前只有主域名croxyproxy被墙，它真正的代理子域名可以直接访问，例如joomdesk.surf，类似bulink跳转cdn.xiaap.com。

希望bulink可以先前置代理croxyproxy，然后在代理的croxyproxy搜索框里输入youtube.com，回车后bulink不是跳转cdn.xiaap.com，而是跳转到croxyproxy的代理子域名joomdesk.surf。

这样bulink可以转用croxyproxy的服务器流量。

**Comment by freefq** [comment]
没有这个想法。在线代理局限性太强，没多大兴趣在这上了。
